apps/contact/api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('list-create/', views.ContactCreateView.as_view())
]

apps/contact/urls.py
from django.urls import path
from .views import contact

app_name = 'contact'

urlpatterns = [
    path('', contact, name='contact')
]

apps/products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('', index, name='index'),
    path('shop-details/<int:pid>/', shop_details, name='shop-details'),
    path('shop-grid/', shop_grid, name='shop_grid'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Ecommerce API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    # swagger
    path('', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('docs/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # admin
    path('admin/', admin.site.urls),

    # allauth
    # path('accounts/', include('allauth.urls')),

    #Api
    # Api
    path('account/api/', include('apps.accounts.api.urls')),
    path('blog/api/', include('apps.blogs.api.urls')),
    path('carts/api/', include('apps.carts.api.urls')),
    path('product/api/', include('apps.products.api.urls')),
    path('contact/api/', include('apps.contact.api.urls')),

    # localhost
    path('', include('apps.products.urls', namespace='products')),
    path('carts/', include('apps.carts.urls', namespace='carts')),
    path('contact/', include('apps.contact.urls', namespace='contact')),
    path('blogs/', include('apps.blogs.urls', namespace='blogs')),
    path('profile/', include('apps.accounts.urls', namespace='accounts'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contact/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Subscribe(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

apps/products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Timestamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(Timestamp):
    title = models.CharField(max_length=21)
    image = models.ImageField(upload_to='categories/', null=True)

    @property
    def normalize_category(self):
        return self.title.replace(' ', ' ').lower()

    def __str__(self):
        return self.title


class Product(Timestamp):
    name = models.CharField(max_length=221)
    categories = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    price = models.FloatField()
    views = models.IntegerField(default=0)
    mid_rate = models.FloatField(default=0)
    description = models.TextField()

    def __str__(self):
        return f'{self.id} | {self.name}'

    @property
    def get_mid_rate(self):
        rates = self.rate_set.all()
        mid = 0
        try:
            mid = sum([i.rate for i in rates]) / rates.count()
        except ZeroDivisionError:
            pass
        self.mid_rate = mid
        self.save()
        return mid


class ProductImage(Timestamp):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_image')
    image = models.ImageField(upload_to='products')

    def __str__(self):
        return f'image of {self.product}'


class Rate(Timestamp):
    RATE = (
        (0, 0),
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.IntegerField(choices=RATE, default=0)

    def __str__(self):
        return f'rate of {self.user.username}'

apps/contact/forms.py
from django import forms
from .models import Contact, Subscribe


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

apps/contact/api/views.py
from rest_framework import generics, status, permissions
from .serialziers import ContactSerializer
from ..models import Contact


class ContactCreateView(generics.ListCreateAPIView):
    # http://127.0.0.1:8000/contact/api/create/
    queryset = Contact.objects.all()
    serializer_class = ContactSerializer

apps/contact/views.py
from django.shortcuts import render
from .models import Contact, Subscribe
from .forms import ContactForm
from apps.products.models import Category


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
    email = request.GET.get('email')
    if email:
        Subscribe.objects.create(email=email)
    ctx = {
        'form': form,
    }
    return render(request, 'product/contact.html', ctx)

apps/products/api/views.py
from rest_framework import generics, status, permissions
from rest_framework.response import Response
from .serializers import CategorySerializer, ProductSerializer, ProductImageSerializer, RateSerializer
from ..models import Category, Product, ProductImage, Rate


class CategoryListAPIView(generics.ListAPIView):
    # http://127.0.0.1:8000/api/category/list/
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class ProductListAPIView(generics.ListAPIView):
    # http://127.0.0.1:8000/api/product/list/
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            qs = qs.filter(name__icontains=q)
        return qs


class RateCreateAPIView(generics.CreateAPIView):
    # http://127.0.0.1:8000/api/product-rate/create/
    queryset = Rate.objects.all()
    serializer_class = RateSerializer
    permission_classes = [permissions.IsAuthenticated]


class UpdateViewsAPIView(generics.RetrieveAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.views += 1
        instance.save()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)

apps/products/views.py
from django.shortcuts import render
from .models import Product
from apps.blogs.models import Post
from django.contrib.auth.decorators import login_required


def index(request):
    posts = Post.objects.order_by('-id')[:3]
    product = Product.objects.all().order_by('-id')
    top_rated_products = product.order_by('-mid_rate')[:6]
    top_viewed_products = product.order_by('-views')[:6]
    latest_products = product[:6]
    s = request.GET.get('s')
    if s:
        product = Product.objects.filter(name__icontains=s)
    ctx = {
        'products': product[:8],
        'posts': posts,
        'latest_products': latest_products,
        'top_rated_products': top_rated_products,
        'top_viewed_products': top_viewed_products,
    }
    return render(request, 'product/index.html', ctx)


@login_required
def shop_details(request, pid):
    product = Product.objects.get(id=pid)
    related_products = Product.objects.order_by('-id')[:4]
    ctx = {
        'product': product,
        'related_products': related_products
    }
    return render(request, 'shop/shop-details.html', ctx)


@login_required
def shop_grid(request):
    products = Product.objects.order_by('-id')[:12]
    last_products = Product.objects.order_by('-id')[:6]
    s = request.GET.get('s')
    if s:
        products = Product.objects.filter(name__icontains=s)
    cat = request.GET.get('cat')
    if cat:
        products = Product.objects.filter(category__category__exact=cat)
    ctx = {
        'products': products,
        'last_products': last_products
    }
    return render(request, 'shop/shop-grid.html', ctx)

templates/product/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="hero hero-normal">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="hero__categories">
                    <div class="hero__categories__all">
                        <i class="fa fa-bars"></i>
                        <span>All categories</span>
                    </div>
                    <ul>
                        {% for category in categories %}
                            <li><a href="#">{{ category }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="hero__search">
                    <div class="hero__search__form">
                        <form method="get">
                            <input type="search" name="s" placeholder="What do you need?">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                    <div class="hero__search__phone">
                        <div class="hero__search__phone__icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="hero__search__phone__text">
                            <h5>+998 90 810 67 63</h5>
                            <span>support 24/7 time</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="breadcrumb-section set-bg" style="max-height: 700px;" data-setbg="{% static 'img/blog/details-hero.jpg.webp' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Contact Us</h2>
                    <div class="breadcrumb__option">
                        <a href="/">Home</a>
                        <span>Contact Us</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="contact spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_phone"></span>
                    <h4>Phone</h4>
                    <p>+998 99 085 23 17</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_pin_alt"></span>
                    <h4>Address</h4>
                    <p>54 Mirzo Ulugbek Avenue, Tashkent, Uzbekistan</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_clock_alt"></span>
                    <h4>Open time</h4>
                    <p>09:00 am to 23:00 pm</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_mail_alt"></span>
                    <h4>Email</h4>
                    <p><a href="https://preview.colorlib.com/cdn-cgi/l/email-protection" class="__cf_email__"
                          data-cfemail="b6ded3dadad9f6d5d9dad9c4dadfd498d5d9db">[email&#160;protected]</a></p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d629.8888178873076!2d69.32506250427465!3d41.32467540280874!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38aef572e5842f55%3A0xa87fc261e04f75ea!2siSystem%20IT%20academy!5e0!3m2!1sen!2s!4v1654413226614!5m2!1sen!2s"
            width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    <div class="map-inside">
        <i class="icon_pin"></i>
        <div class="inside-widget">
            <h4>Tashkent</h4>
            <ul>
                <li>Phone: +998 99 085 23 17</li>
                <li>Add: Ipakchi 1-tor ko'chasi. Tashkent, Uzbekistan</li>
            </ul>
        </div>
    </div>
</div>

<div class="contact-form spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="contact__form__title">
                    <h2>Leave Message</h2>
                </div>
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    {{ form.name }}
                </div>
                <div class="col-lg-6 col-md-6">
                    {{ form.email }}
                </div>
                <div class="col-lg-12 text-center">
                    {{ form.message }}
                    <button type="submit" class="site-btn">SEND MESSAGE</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script>
$('.header__menu>ul>li').removeClass('active')
$('.contact_page').addClass('active')
</script>
{% endblock %}

templates/product/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="hero">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="hero__categories">
                    <div class="hero__categories__all">
                        <i class="fa fa-bars"></i>
                        <span>All Categories</span>
                    </div>
                    <ul>
                        {% for category in categories %}
                             <li><a href="/shop-grid/?cat={{ category }}">{{ category.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="hero__search">
                    <div class="hero__search__form">
                        <form action="get">
                            <input type="text" placeholder="What do yo u need?">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                    <div class="hero__search__phone">
                        <div class="hero__search__phone__icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="hero__search__phone__text">
                            <h5>99-085-23-17</h5>
                            <span>support 24/7 time</span>
                        </div>
                    </div>
                </div>
                <div class="hero__item set-bg" data-setbg="{% static 'img/herp/article6219.jpg' %}">
                    <div class="hero__text">
                        <span>FRUIT FRESH</span>
                        <h2>Vegetable <br/>100% Organic</h2>
                        <p>Free Pickup and Delivery Available</p>
                        <a href="#" class="primary-btn">SHOP NOW</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="categories">
    <div class="container">
        <div class="row">
            <div class="categories__slider owl-carousel">
                {% for category in categories %}
                    <div class="col-lg-3">
                    <div class="categories__item set-bg" data-setbg="{{ category.image.url }}">
                        <h5><a href="{% url 'products:shop_grid' %}">{{ category.title }}</a></h5>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>


<section class="featured spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>Featured Product</h2>
                </div>
                <div class="featured__controls">
                    <ul>
                        <li class="active" data-filter="*">All</li>
                        {% for category in categories %}
                            <li data-filter=".{{ category.normalize_category }}">{{ category }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="row featured__filter" id="product">
            {% for product in products %}
                 <div class="col-lg-3 col-md-4 col-sm-6 mix {{ product.category.normalize_category }}">
                    <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="{{ product.product_image.first.image.url }}">
                        <ul class="featured__item__pic__hover">
                         {% if request.user.is_authenticated %}
                            <li><a class="add-wishlist" data-product="{{ product.id }}">
                                <i class="fa {% if product.id in  wlist_products_id %} fa-heart-circle-minus {% else %} fa-heart-circle-plus {% endif %}"></i>
                            </a></li>
                            <li><a class="add-cart" data-product="{{ product.id }}"><i class="fa fa-cart-arrow-down"></i></a></li>
                            {% else %}
                            <h4 style="background-color: white"><a style="color: red" href="/accounts/login/">You should login!!!</a></h4>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="{% url 'products:shop-details' product.id %}">{{ product.name }}</a></h6>
                        <h5>UZS {{ product.price }}</h5>
                    </div>
                </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>


<div class="banner">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="banner__pic">
                    <img src="{% static 'img/banner/banner-1.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="banner__pic">
                    <img src="{% static 'img/banner/banner-2.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </div>
</div>


<section class="latest-product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="latest-product__text">
                    <h4>Latest Products</h4>
                    <div class="latest-product__slider owl-carousel">
                        <div class="latest-prdouct__slider__item">
                            {% for latest_product in latest_products|slice:':3' %}
                                <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ latest_product.product_image.first.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{ latest_product.name }}</h6>
                                    <span>UZS {{ latest_product.price }}</span>
                                    <pre><code><i class="fa fa-eye"></i> : {{ latest_product.views }}</code></pre>
                                    <pre><code><i class="fa fa-star-half-o"></i> : {{ latest_product.get_mid_rate }}</code></pre>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                        <div class="latest-prdouct__slider__item">
                             {% for latest_product in latest_products|slice:'3:' %}
                                <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ latest_product.product_image.first.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{ latest_product.name }}</h6>
                                    <span>UZS {{ latest_product.price }}</span>
                                    <pre><code><i class="fa fa-eye"></i> : {{ latest_product.views }}</code></pre>
                                    <pre><code><i class="fa fa-star-half-o"></i> : {{ latest_product.get_mid_rate }}</code></pre>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="latest-product__text">
                    <h4>Top Rated Products</h4>
                    <div class="latest-product__slider owl-carousel">
                        <div class="latest-prdouct__slider__item">
                          {% for top_rated_product in top_rated_products|slice:':3' %}
                                <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ top_rated_product.product_image.first.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{ top_rated_product.name }}</h6>
                                    <span>UZS {{ top_rated_product.price }}</span>
                                    <pre><code><i class="fa fa-eye"></i> : {{ top_rated_product.views }}</code></pre>
                                    <pre><code><i class="fa fa-star-half-o"></i> : {{ top_rated_product.get_mid_rate }}</code></pre>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                        <div class="latest-prdouct__slider__item">
                             {% for top_rated_product in top_rated_products|slice:'3:' %}
                                <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ top_rated_product.product_image.first.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{ top_rated_product.name }}</h6>
                                    <span>UZS {{ top_rated_product.price }}</span>
                                    <pre><code><i class="fa fa-eye"></i> : {{ top_rated_product.views }}</code></pre>
                                    <pre><code><i class="fa fa-star-half-o"></i> : {{ top_rated_product.get_mid_rate }}</code></pre>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="latest-product__text">
                    <h4>Review Products</h4>
                    <div class="latest-product__slider owl-carousel">
                        <div class="latest-prdouct__slider__item">
                             {% for top_viewed_product in top_viewed_products|slice:':3' %}
                                <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ top_viewed_product.product_image.first.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{ top_viewed_product.name }}</h6>
                                    <span>UZS {{ top_viewed_product.price }}</span>
                                    <pre><code><i class="fa fa-eye"></i> : {{ top_viewed_product.views }}</code></pre>
                                    <pre><code><i class="fa fa-star-half-o"></i> : {{ top_viewed_product.get_mid_rate }}</code></pre>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                        <div class="latest-prdouct__slider__item">
                           {% for top_viewed_product in top_viewed_products|slice:'3:' %}
                                <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ top_viewed_product.product_image.first.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{ top_viewed_product.name }}</h6>
                                    <span>UZS {{ top_viewed_product.price }}</span>
                                    <pre><code><i class="fa fa-eye"></i> : {{ top_viewed_product.views }}</code></pre>
                                    <pre><code><i class="fa fa-star-half-o"></i> : {{ top_viewed_product.get_mid_rate }}</code></pre>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="from-blog spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title from-blog__title">
                    <h2>From The Blog</h2>
                </div>
            </div>
        </div>
        <div class="row">
             {% for post in posts %}
                <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <img src="{{ post.image.url }}" alt="">
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> {{ post.created_at }}</li>
                        </ul>
                        <h5><a href="{% url 'blog:blog-details' post.id %}">{{ post.title|slice:75 }}</a></h5>
                        <p>{{ post.content|slice:150 }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}